import "./globals.css";
import { StoreProvider } from "@/app/storeProvider";


export const metadata = {
  title: "gestion de stock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`antialiased`}
      >
        <StoreProvider>
            {children}
        </StoreProvider>
      </body>
    </html>
  );
}
